#!/usr/bin/env bash
#Script that check the subdomains
function display_info {
    domain="$1"
    subdomain="$2"
    
    if [ -z "$subdomain" ]; then
        subdomain="www lb-01 web-01 web-02"
    fi

    for sub in $subdomain; do
        result=$(dig $sub.$domain | grep -A1 'ANSWER SECTION:' | awk 'NR==2' | awk '{print $NF}')
	record=$(dig $sub.$domain | grep -A1 'ANSWER SECTION:' | awk 'NR==2' | awk '{print $4}')
        echo "The subdomain $sub is a $record record and points to $result"
    done
}

if [ $# -lt 1 ]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi
domain="$1"
subdomain="$2"
display_info "$domain" "$subdomain"
