#!/usr/bin/env bash
#Script that install a LoadBalancer
apt-get update
apt-get install -y haproxy

echo "ENABLED=1" >> /etc/default/haproxy

systemctl enable haproxy
systemctl restart haproxy

echo 'frontend www
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server web-01 54.162.77.34:80 check
    server web-02 100.25.194.211:80 check
' >> /etc/haproxy/haproxy.cfg

systemctl enable haproxy
systemctl restart haproxy
