#!/usr/bin/env bash
#Script that install and configure Haproxy LoadBalancer
apt-get update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
echo -e "\nfrontend www\n\tbind *:80" >> /etc/haproxy/haproxy.cfg
echo -e "\tdefault_backend servers" >> /etc/haproxy/haproxy.cfg
echo -e "\nbackend servers\n\tbalance roundrobin" >> /etc/haproxy/haproxy.cfg
echo -e "\tserver web1 54.162.77.34:80 check" >> /etc/haproxy/haproxy.cfg
echo -e "\tserver web2 100.25.194.211:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
