#!/usr/bin/env bash
#Script that fixes nginx problem
sed -i 's/ipv6only=on//' /etc/nginx/sites-enabled/default
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
