#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.
cp /etc/hosts ~/hosts.new
sed -i 's/^127.0.0.1.*/127.0.0.2 localhost/g' ~/hosts.new
sed -i 's/^157.240.11.35.*/8.8.8.8 facebook.com/g' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
